set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

if(NOT DEFINED ENV{ZIG} OR NOT DEFINED ENV{GD_ARM_ZIGAR} OR NOT DEFINED ENV{GD_ARM_ZIGRANLIB})
    message(FATAL_ERROR "Set ZIG, GD_ARM_ZIGAR, and GD_ARM_ZIGRANLIB")
endif()

string(REPLACE "\\" "/" GD_ZIG "$ENV{ZIG}")
string(REPLACE "\\" "/" GD_ZIGAR "$ENV{GD_ARM_ZIGAR}")
string(REPLACE "\\" "/" GD_ZIGRANLIB "$ENV{GD_ARM_ZIGRANLIB}")

set(CMAKE_C_COMPILER
    "${GD_ZIG}" cc -target x86_64-windows-gnu
    CACHE STRING "Zig x64 Windows C compiler" FORCE)
set(CMAKE_CXX_COMPILER
    "${GD_ZIG}" c++ -target x86_64-windows-gnu
    CACHE STRING "Zig x64 Windows C++ compiler" FORCE)
set(CMAKE_AR "${GD_ZIGAR}" CACHE FILEPATH "Zig archive wrapper" FORCE)
set(CMAKE_RANLIB "${GD_ZIGRANLIB}" CACHE FILEPATH "Zig ranlib wrapper" FORCE)
set(CMAKE_C_COMPILER_AR "${GD_ZIGAR}" CACHE FILEPATH "Zig C archive wrapper" FORCE)
set(CMAKE_CXX_COMPILER_AR "${GD_ZIGAR}" CACHE FILEPATH "Zig C++ archive wrapper" FORCE)
set(CMAKE_C_COMPILER_RANLIB "${GD_ZIGRANLIB}" CACHE FILEPATH "Zig C ranlib wrapper" FORCE)
set(CMAKE_CXX_COMPILER_RANLIB "${GD_ZIGRANLIB}" CACHE FILEPATH "Zig C++ ranlib wrapper" FORCE)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
