set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86)
if(NOT DEFINED ENV{GD_ARM_ZIGCC} OR
   NOT DEFINED ENV{GD_ARM_ZIGAR} OR
   NOT DEFINED ENV{GD_ARM_ZIGRANLIB})
    message(FATAL_ERROR "Set GD_ARM_ZIGCC, GD_ARM_ZIGAR, and GD_ARM_ZIGRANLIB")
endif()
set(CMAKE_C_COMPILER "$ENV{GD_ARM_ZIGCC}")
set(CMAKE_AR "$ENV{GD_ARM_ZIGAR}")
set(CMAKE_RANLIB "$ENV{GD_ARM_ZIGRANLIB}")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
